# Generated by Django 4.2 on 2023-04-15 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                (
                'sex', models.CharField(blank=True, choices=[('F', 'Male'), ('M', 'Female')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[
                    django.core.validators.RegexValidator(regex='9(1[0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}')])),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
