name: Django Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    env:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: django_ecommerce
      MYSQL_USER: django_ecommerce
      MYSQL_PASSWORD: django_ecommerce

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up test database
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-server
          sudo service mariadb start
          sudo mysql -u root -pmysql -e "CREATE USER '${MYSQL_USER}'@'${MYSQL_HOST}' IDENTIFIED BY '${MYSQL_PASSWORD}'; CREATE DATABASE ${MYSQL_DATABASE}; GRANT ALL PRIVILEGES ON test_${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'${MYSQL_HOST}'; FLUSH PRIVILEGES;"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Django Tests
        run: python manage.py test
